#!/usr/bin/env bash
#prints Best School 10 times but for the 9th iteration, print Best School and then Hi

i=0
while [ $i -le 9 ]
do
	echo "Best School"
	if [ $i -eq 8 ]
	then
		echo "Hi"
	fi
	((i++))
done
