#!/usr/bin/env bash
#prints Best School, displays bad luck for 4th iteration and good luck for 8th iteration otherwise display Best School
i=1
while [ $i -le 10 ]
do 
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
