#!/usr/bin/env bash
#dispays numbers from 1 to 20
#if number is 4, display number and bad luck
#display 9 and bad luck from japan for 9th iteration
#display 17 and badluck from italy for 17th iteration

i=1
while [ $i -le 20 ]
do
	 case  $i in
		4)
			echo "$i"
			echo "bad luck from China"
			;;
		9)
			echo "$i"
			echo "bad luck from japan"
			;;
	 	17)
			echo "$i"
			echo "bad luck from Italy"
			;;
		*)
			echo "$i"
			;;
	esac
	((i++))
done
